# encoding: utf-8
require File.expand_path(File.dirname(__FILE__)) + '/../test_helper'

# This file is generated by the Ruby Holiday gem.
#
# Definitions loaded: data/jewish.yaml
class JewishDefinitionTests < Test::Unit::TestCase  # :nodoc:

  def test_jewish
assert_equal true, true

  end
end
